server:
  port: 8080

spring:
  application:
    name: ecommerce-backend

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name:
      password:

management:
  endpoints:
    web:
      exposure:
        include: health,info
